import { EditorialShell, NewsletterForm, SEOHead } from "@/components/editorial/EditorialKit";
import { Link } from "react-router-dom";

const SITE = "https://regra-na-mao-boxe.lovable.app";

function Page({ title, eyebrow, description, children, slug }: { title: string; eyebrow: string; description: string; children: React.ReactNode; slug: string }) {
  return <EditorialShell><SEOHead title={`${title} | BOXE DE CRIA`} description={description} canonical={`${SITE}/${slug}`} /><section className="container py-14 sm:py-20"><div className="mx-auto max-w-4xl"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#B78A56]">{eyebrow}</div><h1 className="mt-3 font-display text-4xl font-black sm:text-6xl">{title}</h1><p className="mt-5 text-lg leading-8 text-[#C9BDAA]">{description}</p><div className="mt-10 space-y-9 text-[16px] leading-8 text-[#D5C9B8]">{children}</div></div></section></EditorialShell>;
}

export function AboutPage() {
  return <Page slug="sobre" eyebrow="Quem somos" title="Sobre o BOXE DE CRIA" description="Uma marca editorial e educacional criada para tratar o boxe com método, cultura, responsabilidade e linguagem de quem vive a luta."><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">A proposta</h2><p className="mt-3">O BOXE DE CRIA reúne conteúdo técnico, materiais de ensino e cultura de combate. A editoria VISÃO DE CRIA organiza esse conhecimento em artigos que podem ser estudados, consultados e compartilhados.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">Satoshi Nishiuchi</h2><p className="mt-3">Satoshi Nishiuchi é o autor dos materiais publicados pela marca e responsável pela direção editorial do projeto. Esta página evita títulos ou credenciais que não estejam documentados no próprio projeto; quando um conteúdo exigir revisão de outra área profissional, isso deve ser informado na página correspondente.</p></section><section className="rounded-2xl border border-[#B78A56]/30 bg-[#171717] p-6"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#B78A56]">Missão</div><p className="mt-3 font-display text-2xl font-black text-[#F0E6D2]">SER FORTE É SER GENTIL.</p><p className="mt-3">Força sem responsabilidade vira ruído. O projeto busca ensinar boxe sem separar técnica, caráter e cuidado.</p></section><NewsletterForm/></Page>;
}

export function EditorialPolicyPage() {
  return <Page slug="politica-editorial" eyebrow="Transparência" title="Política editorial" description="Como o VISÃO DE CRIA pesquisa, escreve, revisa, corrige e monetiza seu conteúdo."><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">1. Utilidade antes de volume</h2><p className="mt-3">Não publicamos textos apenas para preencher calendário ou exibir anúncios. Cada artigo deve responder uma pergunta real, ensinar algo aplicável ou documentar uma parte relevante da cultura do boxe.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">2. Fontes e afirmações</h2><p className="mt-3">Estudos, regulamentos, estatísticas e citações só devem aparecer quando puderem ser identificados. Não inventamos DOI, entrevistas, números, depoimentos ou experiência prática.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">3. Saúde e segurança</h2><p className="mt-3">Conteúdo de saúde é educacional. Não oferecemos diagnóstico ou prescrição individual. Quando a complexidade do tema exigir, o texto deve receber revisão profissional adequada e declarar seus limites.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">4. Uso de IA</h2><p className="mt-3">Ferramentas de IA podem apoiar organização, pesquisa e revisão, mas não autorizam publicação automática de conteúdo sem verificação. A responsabilidade editorial permanece humana.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">5. Correções e conflitos</h2><p className="mt-3">Erros relevantes devem ser corrigidos e a data de revisão atualizada. Patrocínios, links afiliados e relações comerciais devem ser identificados para que o leitor saiba quando existe interesse econômico.</p></section></Page>;
}

export function AffiliatesPage() {
  return <Page slug="afiliados" eyebrow="Publicidade e comércio" title="Política de afiliados" description="Como tratamos links comissionados e recomendações comerciais."><p>Alguns conteúdos podem conter links de afiliados. Quando isso acontecer, o BOXE DE CRIA poderá receber comissão caso uma compra seja realizada, sem alterar o preço para o leitor.</p><p>Uma comissão não deve determinar uma recomendação técnica. Produtos não testados pessoalmente não serão apresentados como se tivessem sido avaliados na prática. Links afiliados devem ser identificados e usar atributos adequados, como <code className="rounded bg-black/30 px-1">rel=&quot;sponsored noopener&quot;</code>.</p><p>Produtos próprios da marca também podem ser recomendados quando forem pertinentes ao conteúdo. O leitor deve conseguir distinguir claramente conteúdo editorial, produto próprio e publicidade.</p></Page>;
}

export function PrivacyPage() {
  return <Page slug="privacidade" eyebrow="LGPD" title="Política de privacidade" description="Resumo transparente sobre os dados tratados pelo site BOXE DE CRIA."><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">Dados que você fornece</h2><p className="mt-3">Ao entrar no Round Semanal, tratamos nome, e-mail, data do consentimento e origem do cadastro para entregar a newsletter. Não vendemos essa lista.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">Medição e cookies</h2><p className="mt-3">O site pode usar ferramentas de analytics e marketing conforme sua escolha no banner de consentimento. Parâmetros de campanha como UTM, gclid e fbclid podem ser preservados para atribuição e continuidade do checkout.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">Publicidade</h2><p className="mt-3">A infraestrutura do Google AdSense existe no projeto, mas anúncios só devem ser ativados após configuração e aprovação válidas. O site não mede cliques individuais em anúncios.</p></section><section><h2 className="font-display text-2xl font-black text-[#F0E6D2]">Seus direitos</h2><p className="mt-3">Você pode solicitar informações, correção ou exclusão dos dados fornecidos ao projeto por meio dos canais indicados na página de contato. Esta política pode ser atualizada quando a operação ou as ferramentas do site mudarem.</p></section></Page>;
}

export function TermsPage() {
  return <Page slug="termos" eyebrow="Regras de uso" title="Termos de uso" description="Condições gerais para acesso ao conteúdo e aos materiais do BOXE DE CRIA."><p>O conteúdo editorial é fornecido para fins educacionais e informativos. Ele não substitui regulamentos oficiais de eventos, orientação individual de treinador responsável ou avaliação profissional de saúde quando necessária.</p><p>Textos, marcas, ilustrações e materiais próprios são protegidos pela legislação aplicável. Não é permitido reproduzir, revender ou redistribuir produtos digitais protegidos sem autorização.</p><p>Links para plataformas externas, inclusive Hotmart, seguem os termos e políticas dessas plataformas. Preços, disponibilidade e condições comerciais podem ser atualizados na página de produto.</p><p>O BOXE DE CRIA pode corrigir ou atualizar conteúdos para refletir mudanças técnicas, editoriais e operacionais.</p></Page>;
}

export function ContactPage() {
  return <Page slug="contato" eyebrow="Fale com a marca" title="Contato" description="Canais públicos do BOXE DE CRIA para dúvidas editoriais, correções e assuntos comerciais."><section className="grid gap-4 sm:grid-cols-2"><a href="https://instagram.com/boxedecria_" target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/10 bg-[#111] p-6 hover:border-[#B78A56]/40"><div className="font-display text-xl font-black text-[#F0E6D2]">Instagram</div><p className="mt-2 text-sm">@boxedecria_</p></a><a href="https://youtube.com/@criacombat" target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/10 bg-[#111] p-6 hover:border-[#B78A56]/40"><div className="font-display text-xl font-black text-[#F0E6D2]">YouTube</div><p className="mt-2 text-sm">@criacombat</p></a></section><p>Para correções de conteúdo, informe o título ou endereço do artigo e descreva o ponto a ser revisto. Não prometemos prazo fixo de resposta.</p></Page>;
}

export function Simple404() {
  return <EditorialShell><SEOHead title="Página não encontrada | BOXE DE CRIA" description="A página solicitada não foi encontrada." canonical={`${SITE}/404`} /><section className="container py-24 text-center"><div className="text-xs font-bold uppercase tracking-[.2em] text-[#B78A56]">404</div><h1 className="mt-3 font-display text-5xl font-black">Esse round terminou.</h1><p className="mx-auto mt-4 max-w-xl text-[#C9BDAA]">A página que você procurou não existe ou mudou de endereço.</p><div className="mt-7 flex justify-center gap-3"><Link to="/" className="rounded-lg bg-[#C62828] px-5 py-3 font-bold">Voltar ao início</Link><Link to="/artigos" className="rounded-lg border border-white/10 px-5 py-3 font-bold">Abrir artigos</Link></div></section></EditorialShell>;
}
