// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/catalog.ts
var CHECKOUT_URL = "https://pay.hotmart.com/E105828277Q?checkoutMode=0&bid=1779626342467";
var PRODUCTS = [
  {
    id: "manual-do-corner",
    name: "O Manual do C\xF3rner \u2014 Regras do Boxe na M\xE3o",
    price_brl: 49.9,
    pages: 44,
    summary: "Regras, arbitragem e prepara\xE7\xE3o para o canto. Guia visual pr\xE1tico para treinadores e atletas.",
    checkout_url: "https://go.hotmart.com/D105758587D"
  },
  {
    id: "caminho-do-boxeador",
    name: "O Caminho do Boxeador \u2014 Fundamentos T\xE9cnicos",
    price_brl: 67.9,
    pages: 85,
    summary: "Fundamentos t\xE9cnicos e metodologia de aula para o professor de boxe.",
    checkout_url: "https://go.hotmart.com/D105758904F"
  },
  {
    id: "combo-completo",
    name: "Combo Completo \u2014 os dois e-books",
    price_brl: 89.9,
    old_price_brl: 117.8,
    pages: 129,
    summary: "Os dois manuais juntos com 24% de desconto: regras + fundamentos t\xE9cnicos, o m\xE9todo completo do professor.",
    checkout_url: CHECKOUT_URL
  }
];
var FAQ = [
  {
    question: "Como recebo o material?",
    answer: "Por e-mail, em PDF, logo ap\xF3s a confirma\xE7\xE3o do pagamento via Hotmart. Acesso vital\xEDcio no celular, tablet ou computador."
  },
  {
    question: "Qual a diferen\xE7a entre os dois e-books?",
    answer: "O Manual do C\xF3rner foca em regras, arbitragem e prepara\xE7\xE3o para o canto. O Caminho do Boxeador foca em fundamentos t\xE9cnicos e metodologia de aula. Juntos formam o m\xE9todo completo do professor."
  },
  {
    question: "Vale mais a pena comprar o combo?",
    answer: "Sim. O combo sai por R$ 89,90 \u2014 voc\xEA economiza R$ 27,90 em rela\xE7\xE3o a comprar os dois separadamente, com 24% de desconto."
  },
  {
    question: "E se eu n\xE3o gostar?",
    answer: "Voc\xEA tem 7 dias para pedir reembolso. 100% do seu dinheiro de volta, sem perguntas. Risco zero."
  }
];

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar produtos",
  description: "Lista os e-books e o combo do Boxe de Cria com pre\xE7o em reais, n\xFAmero de p\xE1ginas e link de checkout.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PRODUCTS, null, 2) }],
    structuredContent: { products: PRODUCTS }
  })
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Detalhes de um produto",
  description: "Retorna os detalhes de um e-book do Boxe de Cria pelo seu id (manual-do-corner, caminho-do-boxeador, combo-completo).",
  inputSchema: {
    id: z.string().describe("Id do produto, como retornado por list_products.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const product = PRODUCTS.find((p) => p.id === id.trim());
    if (!product) {
      throw new ToolError(
        `Produto "${id}" n\xE3o encontrado. Use list_products para ver os ids dispon\xEDveis.`
      );
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-faq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_faq_default = defineTool3({
  name: "list_faq",
  title: "Perguntas frequentes",
  description: "Lista as perguntas frequentes p\xFAblicas do site Boxe de Cria (entrega, diferen\xE7as entre os e-books, combo e garantia).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FAQ, null, 2) }],
    structuredContent: { faq: FAQ }
  })
});

// src/lib/mcp/index.ts
var projectRef = "vmarxwfiizzkwvillsqm";
var mcp_default = defineMcp({
  name: "boxe-de-cria-guia-essencial",
  title: "Boxe de Cria: Guia Essencial",
  version: "0.1.0",
  instructions: "Ferramentas do Boxe de Cria (requer login). Use `list_products` para ver os e-books, pre\xE7os e links de checkout, `get_product` para detalhes de um item e `list_faq` para as d\xFAvidas frequentes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, list_faq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
