create extension if not exists pgcrypto;

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.authors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  bio text not null default '',
  role text not null default 'Autor',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  body jsonb not null default '{}'::jsonb,
  cover_image text,
  category_id uuid references public.categories(id) on delete set null,
  author_id uuid references public.authors(id) on delete set null,
  status text not null default 'draft' check (status in ('draft','review','published','archived')),
  featured boolean not null default false,
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  read_time text,
  seo_title text,
  seo_description text,
  reviewer_name text,
  last_reviewed_at timestamptz
);

create table if not exists public.newsletter_leads (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  email text not null unique check (char_length(email) between 5 and 254),
  consent boolean not null default false,
  consent_at timestamptz,
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.article_views (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  session_id text,
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.outbound_clicks (
  id bigint generated by default as identity primary key,
  post_slug text,
  target_type text not null check (target_type in ('product','affiliate','external','newsletter')),
  target_url text not null,
  label text,
  source text,
  created_at timestamptz not null default now()
);

create index if not exists posts_status_published_idx on public.posts(status, published_at desc);
create index if not exists posts_category_idx on public.posts(category_id);
create index if not exists article_views_slug_created_idx on public.article_views(post_slug, created_at desc);
create index if not exists outbound_clicks_slug_created_idx on public.outbound_clicks(post_slug, created_at desc);

alter table public.categories enable row level security;
alter table public.authors enable row level security;
alter table public.posts enable row level security;
alter table public.newsletter_leads enable row level security;
alter table public.article_views enable row level security;
alter table public.outbound_clicks enable row level security;

create policy "public read categories" on public.categories for select using (true);
create policy "public read authors" on public.authors for select using (true);
create policy "public read published posts" on public.posts for select using (status = 'published');
create policy "public newsletter signup" on public.newsletter_leads for insert with check (consent = true and email like '%@%');
create policy "public article view insert" on public.article_views for insert with check (char_length(post_slug) between 1 and 200);
create policy "public outbound click insert" on public.outbound_clicks for insert with check (char_length(target_url) between 1 and 2000);

insert into public.categories(name, slug, description) values
('Técnica e Treino','tecnica-e-treino','Fundamentos, golpes, deslocamentos, defesa e construção do treino de boxe.'),
('Saúde do Atleta','saude-do-atleta','Conteúdo educacional sobre cuidado, prevenção, recuperação e limites do corpo no esporte de combate.'),
('Equipamentos','equipamentos','Guias práticos para escolher, usar e conservar luvas, bandagens e equipamentos de treino.'),
('História e Cultura','historia-e-cultura','Memória, personagens, escolas e cultura que formaram o boxe.'),
('Formação de Treinadores','formacao-de-treinadores','Didática, organização de aula, observação técnica e desenvolvimento de atletas.')
on conflict (slug) do nothing;

insert into public.authors(name, slug, bio, role) values
('Satoshi Nishiuchi','satoshi-nishiuchi','Autor e responsável pela direção editorial do BOXE DE CRIA.','Autor e editor')
on conflict (slug) do nothing;
